apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-world-template
  title: Hello World
  description: Says Hello to a specified name.
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: You are about to say hello to your first Backstage Template
      required:
        - name
      properties:
        name:
          type: string
        tasks: 
          type: array
          title: Tasks
          items: 
            type: object
            required: 
              - title
            properties: 
              title:
                type: string
                title: Title
                description: A sample title
              
              details: 
                type: string
                title: Task details
                description: Enter the task details
              done: 
                type: boolean
                title: Done?
                default: false
              
            
          
        
          

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.name }} and {% for i in [1,2,3,4,5] %} {{ i }} {% endfor %}!'
