apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-world-template
  title: Hello World
  description: Says Hello to a specified name.
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: You are about to say hello to your first Backstage Template
      required:
        - name
      properties:
        name:
          type: string
        tasks: 
          type: array
          title: Remotes
          items: 
            type: object
            required: 
              - app
              - location
            properties: 
              app:
                type: string
                title: Application
                description: An application
              location: 
                type: string
                title: location
                description: Enter location of application
              
              
            
          
        
          

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.name }} and {% for tas in parameters.tasks -%} ${{ tas.app }} : ${{ tas.location }}, \\n {%- endfor %}!'
